version: '3.6'
services:
  hasura:
    image: hasura/graphql-engine:v2.16.1.cli-migrations-v3
    ports:
      - '8888:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anyone
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: naming_convention
